openapi: 3.0.0
info:
  title: AdmissionBook API
  version: 1.0.0
  description: API for managing hospital admission books

# ✅ Global security setup (all routes require token)
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /admissionbook:
    post:
      summary: Create a new AdmissionBook entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nic
                - bht
                - name
                - dailyno
                - yearlyno
                - city
                - stateProvince
                - postalCode
                - country
                - streetAddress
                - age
                - admittedDate
                - reason
                - allergies
                - phone
                - transferCategory
                - wardNo
                - livingStatus
              properties:
                nic:
                  type: string
                bht:
                  type: integer
                name:
                  type: string
                dailyno:
                  type: string
                yearlyno:
                  type: string
                city:
                  type: string
                stateProvince:
                  type: string
                postalCode:
                  type: string
                country:
                  type: string
                streetAddress:
                  type: string
                age:
                  type: integer
                admittedDate:
                  type: string
                  format: date
                reason:
                  type: string
                allergies:
                  type: string
                phone:
                  type: string
                transferCategory:
                  type: string
                dischargeDate:
                  type: string
                  format: date
                  nullable: true
                wardNo:
                  type: string
                livingStatus:
                  type: string
      responses:
        '201':
          description: AdmissionBook Created Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  newAdmissionBook:
                    type: object
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
